name: minify
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          directory: 'src'
          output: 'dist'

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4.5.1
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: dist
